### PR TITLE
Supressed Uncaught TypeError: listener is not a function

### PR DESCRIPTION
**Pull request by mikkelwf**
I fixed an error with new code.

The internal `handleChange` seems to try to execute listeners that doesn't exist. I dont know if it has something to do with my refactor.

But i added a simple check to see if the listener exists, and now the component works as expected.

### CODE REVIEW

**Comment by malte-wessel** [comment]
when does this happen?

**Comment by mikkelwf** [comment]
I tried out my app in the chrome emulator for different devices. Whenever i change device (resolution), it threw the error. And the props didn't update.
I use this hoc in fairly complex layouts, where nested elements are wrapped in this, so i don't know if rerendering the parent element (and thus rerendering the connected element) trigger this.
Adding more complex test cases might also be a good idea..

**Comment by mikkelwf** [comment]
the update is pretty much unusable in my app, so i would appreciate you merging in this fix...

**Comment by malte-wessel** [comment]
fixed it in an own commit. thanks though!

**Comment by mikkelwf** [comment]
super.. thanks.. :)

**Pull request closed without merging**
